---

  - name: Copy vim-specific configuration
    copy:
      src: ~/work/src/github.com/alkurbatov/dotfiles/.vim
      dest: /root
      owner: root
      mode: 0644

  - name: Copy other configuration files
    copy:
      src: "{{item}}"
      dest: /root
      owner: root
      mode: 0644
    with_fileglob:
      - ~/work/src/github.com/alkurbatov/dotfiles/.bashrc
      - ~/work/src/github.com/alkurbatov/dotfiles/.gitconfig
      - ~/work/src/github.com/alkurbatov/dotfiles/.inputrc
      - ~/work/src/github.com/alkurbatov/dotfiles/.vimrc
