#!/bin/bash

# This file is a part of Dotfiles project
#
# Copyright (C) 2013-2021, Alexander Kurbatov <sir.alkurbatov@yandex.ru>
#
# Dotfiles is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Dotfiles is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# Purprose:
# Prepare fresh system for work.

set -ev

# Emacs
brew install emacs
brew install aspell
brew install multimarkdown

# C++
brew install clang-format
brew install cmake
brew install cppcheck                                                                                                                   [alkurbatov@Byaka]
brew install doxygen

# Python
brew install python@3.9
brew install virtualenvwrapper

# JavaScript
brew install node@16
brew link node@16
brew install jq

# Scripting
brew install shellcheck

# Administration
brew install ansible
brew install ansible-lint
brew install inetutils
brew install md5sha1sum
brew install mc

# Utilities
brew install ag
brew install fd
brew install gpg
brew install pinentry-mac
brew install wget
brew install --cask xquartz

# Setup the default layout.
mkdir -p ~/work/{bin,etc,pkg,src,tmp}
mkdir -p ~/work/src/github.com/alkurbatov
mkdir -p ~/work/src/git.acronis.com/alkurbatov

# Precreate SSH folders.
mkdir -p  ~/.ssh/controlmasters

# Copy settings from my dotfiles.
cp ~/work/src/github.com/alkurbatov/dotfiles/.zsh* ~/
cp -r ~/work/src/github.com/alkurbatov/dotfiles/.config ~/
cp -r ~/work/src/github.com/alkurbatov/dotfiles/.emacs* ~/
cp ~/work/src/github.com/alkurbatov/dotfiles/.tmux.conf ~/
cp ~/work/src/github.com/alkurbatov/dotfiles/git/.gitconfig ~/

# Install ZSH plugins.
git clone https://github.com/MichaelAquilina/zsh-you-should-use.git ~/.zsh/zsh-you-should-use
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions

# Tweak Finder
defaults write com.apple.Finder AppleShowAllFiles -bool true
defaults write com.apple.Finder _FXShowPosixPathInTitle -bool true
defaults write com.apple.Finder ShowStatusBar -bool true
defaults write com.apple.finder NewWindowTarget -string "PfHm"
defaults write com.apple.Finder NewWindowTargetPath -string "file:///Users/alkurbatov/"
killall Finder

# Make it possible to repeat the same keypress many times by holding it down.
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
