#!/bin/bash

# This file is a part of Scripts project
#
# Copyright (C) 2017, Alexander Kurbatov <sir.alkurbatov@yandex.ru>
#
# Scripts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Scripts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# Purprose:
# Completely reinstall Virtuozzo Automator Agent
# and clean up all required folders.

yum groupremove -y 'VA Agent'
yum remove va-*-debuginfo va-agent-swamon

rm -rf /var/opt/pva
rm -rf /var/log/pva
rm -rf /opt/pva

yum clean all
yum groupinstall -y 'VA Agent'
yum install -y va-agent-storage va-pp-httpd va-*-debuginfo va-agent-swamon

for i in va-agent httpd; do
    systemctl start ${i}

    if [ ${PIPESTATUS[0]} != 0 ]; then
        echo "Failed to start ${i} service"
        exit 1
    fi
done

