---
- hosts: master,hci-2,hci-3
# Tags:
# initial - a marked action can be executed almost under any conditions and
#           does some initial tweaking.
# partial - a marked action can be executed on a partial installation, e.g.
#           without a cluster or a compute service.
# cluster - a marked action requires a deployed cluster.
# compute - a marked action requires a deployed compute service.

  tasks:
    - name: Disable the Shaman daemon
      systemd:
        name: shaman@Waterdeep
        state: stopped
        masked: yes
      tags:
        - initial

    - name: Add VZLinux Base repository
      yum_repository:
        file: vzlinux
        name: virtuozzolinux-base
        description: Virtuozzo Linux base repository
        mirrorlist: http://kojistorage.eng.sw.ru/vzlinux/mirrorlist/mirrors-7-os
        gpgcheck: no
      tags:
        - initial
        - partial

    - name: Add VZLinux Updates repository
      yum_repository:
        file: vzlinux
        name: virtuozzolinux-updates
        description: Virtuozzo Linux updates repository
        mirrorlist: http://kojistorage.eng.sw.ru/vzlinux/mirrorlist/mirrors-7-updates
        gpgcheck: no
      tags:
        - initial
        - partial

    - name: Add VZLinux Base debuginfo repository
      yum_repository:
        file: vzlinux
        name: virtuozzolinux-base-debuginfo
        description: Virtuozzo Linux base debuginfo repository
        mirrorlist: http://kojistorage.eng.sw.ru/vzlinux/mirrorlist/mirrors-7-os-debug
        gpgcheck: no
      tags:
        - initial
        - partial

    - name: Add VZLinux Updates debuginfo repository
      yum_repository:
        file: vzlinux
        name: virtuozzolinux-updates-debuginfo
        description: Virtuozzo Linux updates debuginfo repository
        mirrorlist: http://kojistorage.eng.sw.ru/vzlinux/mirrorlist/mirrors-7-updates-debug
        gpgcheck: no
      tags:
        - initial
        - partial

    - name: Add UI testing repository
      yum_repository:
        file: hci-ui
        name: hci-ui
        description: UI testing repository
        baseurl: http://kojistorage.eng.sw.ru/mash/hci-3.0-ui/latest/x86_64/os/
        priority: 51
        gpgcheck: no
      when: inventory_hostname == "master"
      tags:
        - initial
        - partial

    - name: Disable the ready kernel repository
      ini_file:
        path: /etc/yum.repos.d/readykernel.repo
        section: readykernel
        option: enabled
        value: 0
        backup: no
      tags:
        - initial
        - partial

    - name: Install software
      yum: state=present name="{{item}}"
      with_items:
        - crudini
        - curl
        - gcc-c++
        - git
        - htop
        - iotop
        - iproute
        - libffi-devel
        - libxml2-devel
        - libxslt-devel
        - mc
        - mlocate
        - patch
        - psacct
        - python-virtualenv
        - rh-python36-python-debuginfo
        - screen
        - strace
        - vim
        - yum-utils
        - wget
        - zsh
      tags:
        - partial

    - name: Install the ack utility
      get_url:
        url: https://beyondgrep.com/ack-2.22-single-file
        dest: /usr/bin/ack
        mode: 0755
      tags:
        - initial
        - partial

    - name: Make ZSH default shell
      command: chsh -s /bin/zsh
      tags:
        - partial

    - name: Copy configuration
      copy:
        src: "{{item}}"
        dest: /root
        owner: root
        mode: 0644
      with_fileglob:
        - ~/work/src/github.com/alkurbatov/dotfiles/.inputrc
        - ~/work/src/github.com/alkurbatov/dotfiles/.vimrc
        - ~/work/src/github.com/alkurbatov/dotfiles/.zsh*
      tags:
        - partial

    - name: Copy vim-specific configuration
      copy:
        src: ~/work/src/github.com/alkurbatov/dotfiles/.vim
        dest: /root
        owner: root
        mode: 0644
      tags:
        - partial

    - name: Create the work folder
      file: path=/root/work/bin state=directory
      tags:
        - partial

    - name: Copy handy scripts
      copy:
        src: "{{item}}"
        dest: /root/work/bin
        owner: root
        mode: 0644
      with_fileglob:
        - ~/work/src/github.com/alkurbatov/dotfiles/bin/reset-hci-logs
        - ~/work/src/github.com/alkurbatov/dotfiles/bin/update-docker
      tags:
        - partial

    - name: Create the .ssh directory
      file: path=/root/.ssh state=directory
      tags:
        - initial
        - partial

    - name: Copy SSH keys
      copy:
        src: ~/.ssh/hci_rsa.pub
        dest: /root/.ssh/authorized_keys
        owner: root
        mode: 0644
      tags:
        - initial
        - partial

    - name: Remove previous installation of the autosuggestion plugin
      file:
        path: ~/.zsh/zsh-autosuggestions
        state: absent
      tags:
        - partial

    - name: Install autosuggestion plugin
      command: git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
      tags:
        - partial

    - name: Extend token lifetime
      command: "{{item}}"
      with_items:
      - /usr/bin/crudini --set ~vstoradmin/etc/keystone/keystone.conf token expiration 360000
      - systemctl restart vstorage-ui-keystone-admin vstorage-ui-keystone-public
      when: inventory_hostname == "master"
      tags:
        - compute

    - name: Update locate DB
      command: /usr/bin/updatedb
      tags:
        - partial

    - name: Configure OpenStack environment
      shell: "{{item}}"
      with_items:
      - echo "# export OS_AUTH_URL=https://127.0.0.1/identity/" >> /root/.zshenv
      - echo "export OS_AUTH_URL=https://127.0.0.1:5000/v3" >> /root/.zshenv
      - echo "# export OS_DOMAIN_ID=default" >> /root/.zshenv
      - echo "export OS_PROJECT_DOMAIN_NAME=Default" >> /root/.zshenv
      - echo "export OS_IDENTITY_API_VERSION=3" >> /root/.zshenv
      - echo "export OS_PROJECT_NAME=admin" >> /root/.zshenv
      - echo "export OS_USER_DOMAIN_NAME=Default" >> /root/.zshenv
      - echo "export OS_USERNAME=admin" >> /root/.zshenv
      - echo "export OS_PASSWORD=1q2w3eQAZ" >> /root/.zshenv
      when: inventory_hostname == "master"
      tags:
        - partial

    - name: Configure Vstoradmin environment
      shell: "{{item}}"
      become: yes
      become_user: vstoradmin
      with_items:
      - echo ". /opt/rh/rh-python36/enable" >> /usr/libexec/vstorage-ui-backend/.bashrc
      - echo ". ~/venv/bin/activate" >> /usr/libexec/vstorage-ui-backend/.bashrc
      - echo "export UI_BACKEND_CONFIG=~/etc/backend.cfg" >> /usr/libexec/vstorage-ui-backend/.bashrc
      tags:
        - partial

    - name: Allow anonymous access to Agent
      replace:
        path: /etc/nginx/conf.d/vstorage-ui-agent.conf
        regexp: 'ssl_verify_client on'
        replace: 'ssl_verify_client off'
        backup: no
      tags:
        - partial

    - name: Restart Nginx to apply the latest changes
      systemd:
        name: nginx
        state: restarted
      tags:
        - partial

    - name: Create very small OpenStack flavor
      command: "openstack --insecure flavor create --ram 32 --disk 1 super-tini"
      when: inventory_hostname == "master"
      tags:
        - compute

    - name: Set cluster's replicas to 3
      command: "vstorage -c Waterdeep set-attr -R -p / replicas=3"
      when: inventory_hostname == "master"
      tags:
        - cluster

    - name: Start the psacct service
      systemd:
        name: psacct
        enabled: True
        state: started
      tags:
        - partial

