---
- hosts: master

  tasks:
    - name: Add VZLinux Base reporitory
      yum_repository:
        file: vzlinux
        name: virtuozzolinux-base
        description: Virtuozzo Linux base repository
        mirrorlist: http://repo.virtuozzo.com/vzlinux/mirrorlist/mirrors-7-os
        gpgcheck: no

    - name: Add VZLinux Updates reporitory
      yum_repository:
        file: vzlinux
        name: virtuozzolinux-updates
        description: Virtuozzo Linux updates repository
        mirrorlist: http://repo.virtuozzo.com/vzlinux/mirrorlist/mirrors-7-updates
        gpgcheck: no

    - name: Add VZLinux Base debuginfo repository
      yum_repository:
        file: vzlinux
        name: virtuozzolinux-base-debuginfo
        description: Virtuozzo Linux base debuginfo repository
        mirrorlist: http://repo.virtuozzo.com/vzlinux/mirrorlist/mirrors-7-os-debug
        gpgcheck: no

    - name: Add VZLinux Updates debuginfo repository
      yum_repository:
        file: vzlinux
        name: virtuozzolinux-updates-debuginfo
        description: Virtuozzo Linux updates debuginfo repository
        mirrorlist: http://repo.virtuozzo.com/vzlinux/mirrorlist/mirrors-7-updates-debug
        gpgcheck: no

    - name: Install software
      yum: state=present name={{ item }}
      with_items:
      - crudini
      - curl
      - git
      - htop
      - iproute
      - mc
      - mlocate
      - rh-python34-python-debuginfo
      - vim
      - wget
      - zsh

    - name: Install the ack utility
      get_url:
        url: https://beyondgrep.com/ack-2.22-single-file
        dest: /usr/bin/ack
        mode: 0755

    - name: Make ZSH default shell
      command: chsh -s /usr/bin/zsh

    - name: Copy configuration
      copy:
        src: "{{ item }}"
        dest: /root
        owner: root
        mode: 644
      with_fileglob:
      - ~/work/src/github.com/alkurbatov/dotfiles/.inputrc
      - ~/work/src/github.com/alkurbatov/dotfiles/.vimrc
      - ~/work/src/github.com/alkurbatov/dotfiles/.zsh*

    - name: Install autosuggestion plugin
      command: git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions

    - name: Extend token lifetime
      command: "{{ item }}"
      with_items:
      - /usr/bin/crudini --set ~vstoradmin/etc/keystone/keystone.conf token expiration 360000
      - systemctl restart vstorage-ui-keystone-admin vstorage-ui-keystone-public

    - name: Update locate DB
      command: /usr/bin/updatedb

    - name: Configure OpenStack environment
      shell: "{{ item }}"
      with_items:
      - echo "# export OS_AUTH_URL=https://127.0.0.1/identity/" >> /root/.zshenv
      - echo "export OS_AUTH_URL=https://127.0.0.1:5000/v3" >> /root/.zshenv
      - echo "export OS_DOMAIN_ID=default" >> /root/.zshenv
      - echo "export OS_IDENTITY_API_VERSION=3" >> /root/.zshenv
      - echo "export OS_PROJECT_NAME=admin" >> /root/.zshenv
      - echo "export OS_USERNAME=admin" >> /root/.zshenv
      - echo "export OS_PASSWORD=1q2w3eQAZ" >> /root/.zshenv

