---
# The playbook contains the recipes which are not used in the other playbooks
# but could be usable from time to time.

  - name: Add virtual IP
    command: "{{ item }} chdir=/etc/sysconfig/network-scripts/"
    with_items:
    - /usr/bin/cp ifcfg-eth0 ifcfg-eth0:1
    - /usr/bin/sed -i "s/eth0/eth0:1/" ifcfg-eth0:1
    - /usr/bin/sed -i "s/BOOTPROTO=dhcp/IPADDR=192.168.56.103/" ifcfg-eth0:1
    - /usr/bin/sed -i "s/IPV6INIT=yes/IPV6INIT=no/" ifcfg-eth0:1
    - /usr/sbin/ifup eth0:1

  - name: Disable iptables
    command: "{{ item }}"
    with_items:
    - systemctl stop iptables
    - systemctl disable iptables

  - name: Allow external login to Postgress
    command: "psql -d vstoradmin -c \"ALTER USER vstoradmin WITH PASSWORD '1q2w3eQAZ'\""
    become: yes
    become_user: postgres
    when: inventory_hostname == "master"

  - name: Disable ntpdate, KVM will sync the clock
    systemd:
      name: ntpdate
      enabled: False

  - name: Start the psacct service
    systemd:
      name: psacct
      enabled: True
      state: started

  - name: Stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: False

  - name: Create the stack user
    user:
      name: stack
      shell: /bin/bash
      home: /opt/stack
      create_home: yes

  - name: Add the stack users to sudoers
    command: "echo \"stack ALL=(ALL) NOPASSWD: ALL\" | tee /etc/sudoers.d/stack"

  - name: Install devstack
    command: "git clone https://git.openstack.org/openstack-dev/devstack"
    become: yes
    become_user: stack

  - name: Purge redundant software
    dnf: state=absent name="{{item}}" autoremove=yes
    with_items:
      - abrt
      - bluez
      - iwl5000-firmware
      - iwl2030-firmware
      - iwl6000g2a-firmware
      - iwl4965-firmware
      - iwl3945-firmware
      - iwl100-firmware
      - iwl6000g2b-firmware
      - iwl135-firmware
      - iwl1000-firmware
      - iwl6000-firmware
      - iwl7260-firmware
      - iwl3160-firmware
      - iwl2000-firmware
      - iwl105-firmware
      - iwl6050-firmware
      - iwl5150-firmware
      - nano
      - wireless-tools
      - wpa_supplicant

  - name: Install virtualization support
    dnf: state=present name="{{item}}"
    with_items:
      - cockpit-machines
      - libvirt
      - libvirt-client
      - libvirt-python
      - qemu-img
      - qemu-kvm
      - virt-install
      - virt-manager

  - name: Install Xserver for X11 forwarding
    dnf: state=present name="{{item}}"
    with_items:
      - mesa-dri-drivers
      - xorg-x11-drv-evdev
      - xorg-x11-drv-fbdev
      - xorg-x11-drv-intel
      - xorg-x11-drv-libinput
      - xorg-x11-drv-vesa
      - xorg-x11-font-utils
      - xorg-x11-server-Xorg
      - xorg-x11-server-common
      - xorg-x11-server-utils
      - xorg-x11-utils
      - xorg-x11-xauth
      - xorg-x11-xinit
      - xorg-x11-xkb-extras

  - name: Enable the nested virtualization
    replace:
      path: /etc/modprobe.d/kvm.conf
      regexp: '#options kvm_intel nested=1'
      replace: 'options kvm_intel nested=1'
      backup: no

  - name: Enable additional features for the nested virtualization
    shell: "{{item}}"
    with_items:
      - echo "options kvm-intel enable_shadow_vmcs=1" >> /etc/modprobe.d/kvm.conf
      - echo "options kvm-intel enable_apicv=1" >> /etc/modprobe.d/kvm.conf
      - echo "options kvm-intel ept=1" >> /etc/modprobe.d/kvm.conf

  - name: Disable reverse path filtering (default) for the nested virtualization
    sysctl:
      name: net.ipv4.conf.default.rp_filter
      value: 0
      state: present
      reload: yes

  - name: Disable reverse path filtering (all) for the nested virtualization
    sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: 0
      state: present
      reload: yes

  - name: Add the epel repository
    yum:
      state: present
      name: epel-release
