# The playbook contains the recipes which are not used in the other playbooks
# but could be usable from time to time.

  tasks:
    - name: Add virtual IP
      command: "{{ item }} chdir=/etc/sysconfig/network-scripts/"
      with_items:
      - /usr/bin/cp ifcfg-eth0 ifcfg-eth0:1
      - /usr/bin/sed -i "s/eth0/eth0:1/" ifcfg-eth0:1
      - /usr/bin/sed -i "s/BOOTPROTO=dhcp/IPADDR=192.168.56.103/" ifcfg-eth0:1
      - /usr/bin/sed -i "s/IPV6INIT=yes/IPV6INIT=no/" ifcfg-eth0:1
      - /usr/sbin/ifup eth0:1

    - name: Disable iptables
      command: "{{ item }}"
      with_items:
      - systemctl stop iptables
      - systemctl disable iptables

    - name: Allow external login to Postgress
      command: "psql -d vstoradmin -c \"ALTER USER vstoradmin WITH PASSWORD '1q2w3eQAZ'\""
      become: yes
      become_user: postgres
      when: inventory_hostname == "master"
      tags:
        - partial

    - name: Disable ntpdate, KVM will sync the clock
      systemd:
        name: ntpdate
        enabled: False
      tags:
        - partial

    - name: Start the psacct service
      systemd:
        name: psacct
        enabled: True
        state: started
      tags:
        - partial
