---
  - include: common/tasks/sync_my_configs.yaml

  - name: Enable the hci-devel repository
    ini_file:
      dest: /etc/yum.repos.d/hci-devel.repo
      section: hci-devel
      option: enabled
      value: "1"

  - name: Disable the readykernel repository
    ini_file:
      path: /etc/yum.repos.d/readykernel.repo
      section: readykernel
      option: enabled
      value: "0"
      backup: no

  - name: Add the aux repository
    yum_repository:
      file: aux
      name: aux
      description: UI testing repository
      baseurl: http://kojistorage.eng.sw.ru/mash/hci-4.0.0-vz/latest/x86_64/os/
      priority: "100"
      gpgcheck: no

  - name: Install additional software for work
    yum:
      state: present
      name:
        - curl
        - gdb
        - gcc-c++
        - git
        - htop
        - iotop
        - iproute
        - libffi-devel
        - libxml2-devel
        - libxslt-devel
        - lsof
        - mc
        - mlocate
        - patch
        - python-virtualenv
        - rh-python36-python-debug
        - screen
        - strace
# FIXME (alkurbatov): Find a way to install server_searcher without epel.
#        - the_silver_searcher
        - vim
        - yum-utils
        - wget
    notify:
      - Update locate DB

  - name: Create the work folder
    file:
      path: /root/work/bin
      state: directory

  - name: Copy handy scripts
    copy:
      src: "{{item}}"
      dest: /root/work/bin
      owner: root
      mode: 0644
    with_fileglob:
      - ~/work/src/github.com/alkurbatov/dotfiles/bin/reset-hci-logs

  - name: Copy developer keys and ssh config
    copy:
      src: "{{item}}"
      dest: /root/.ssh
      owner: root
      mode: 0600
    with_fileglob:
      - ~/.ssh/acronis_rsa
      - ~/.ssh/stash_rsa
      - workstand.setup/files/config
    when: role_in_cluster == "controller"

  - name: Increase nginx logs verbosity
    replace:
      path: /etc/nginx/nginx.conf
      regexp: 'error_log /var/log/nginx/error.log;'
      replace: 'error_log /var/log/nginx/error.log warn;'
      backup: no
    notify:
      -  Restart nginx

# FIME (alkurbatov): Use templates to somehow reduce the code duplication.
  - name: Allow anonymous access to Agent
    replace:
      path: /etc/nginx/conf.d/vstorage-ui-agent.conf
      regexp: "ssl_verify_client on"
      replace: "ssl_verify_client off"
      backup: no
    when: agent_access == "external"
    notify:
      -  Restart nginx

  - name: Disable anonymous access to Agent
    replace:
      path: /etc/nginx/conf.d/vstorage-ui-agent.conf
      regexp: "ssl_verify_client off"
      replace: "ssl_verify_client on"
      backup: no
    when: agent_access == "local"
    notify:
      -  Restart nginx

  - name: Generate OpenStack credentials
    command: kolla-ansible post-deploy
    become: yes
    become_user: vstoradmin
    register: cred_gen_result
    changed_when: cred_gen_result.stdout is search('changed=1')
    when: role_in_cluster == "controller"
    notify:
      - Inject OpenStack credentials

  - name: Disable the Shaman daemon
    systemd:
      name: shaman@{{ cluster_name }}
      state: stopped
      masked: yes

  - name: Set cluster's replicas to 3
    command: "vstorage -c {{ cluster_name }} set-attr -R -p / replicas=3"
    when: role_in_cluster == "controller"

# FIXME (alkurbatov): I doubt that we can do it more then once.
  - name: Create very small OpenStack flavor
    command: "openstack --insecure flavor create --ram 64 --disk 1 super-tini"
    when: role_in_cluster == "controller"

  - name: Extend keystone token lifetime
    ini_file:
      dest: /usr/libexec/vstorage-ui-backend/etc/keystone/keystone.conf
      section: token
      option: expiration
      value: "360000"
    when: role_in_cluster == "controller"
    notify:
      - Restart keystone-admin
      - Restart vstorage-ui-keystone-public

  - name: Enable tracebacks in Backend responces
    replace:
      path: /usr/libexec/vstorage-ui-backend/etc/backend.cfg
      regexp: '(TRACE_MESSAGES =) False'
      replace: '\1 True'
      backup: no
    when: role_in_cluster == "controller"
    notify:
      -  Restart vstorage-ui-backend
